#SERVER
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      show-sql: true
      properties:
        hibernate:
          format-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
    generate-ddl: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-on-validation-error: true
    clean-disabled: false
  logging:
    level:
      root: DEBUG
token:
  signing:
    key: 6B58703273357638792F423F4528482B4D6251655468576D5A7134743777217A25432A462D4A614E645267556B58703273357638792F423F4528482B4D6251655468576D5A7134743777217A25432A462D4A614E64526755
    expiration: 86400000 # a day
    refresh-token:
      expiration: 604800000

#OMDB
org:
  example:
    omdb:
      url: http://www.omdbapi.com
      apikey: 90e9ce58

#SWAGGER
springfox:
  documentation:
    swagger-ui:
      path: /swagger-ui
      url: http://localhost:8080/swagger-ui.html
